### ISSUE TITLE
Feature Request: Save/Load Rolls Improvements

### ISSUE THREAD

**Issue by PanoramicPanda** [JasonCostanza/Dice-Vault#28]
**Is your feature request related to a problem? Please describe.**
I feel like the flow of Saving and Loading the Session Rolls has some room for improvements.

**Describe the solution you'd like**
- On symbiote load, check if session storage has rolls. If so, load them automatically.
- If there are new or edited rolls that haven't been saved, highlight the Save Rolls button in some way to make it obvious that there are "Unsaved Changes".
- If we're auto-loading saved rolls, have a way to "Unload" the rolls, without clearing session storage. This gives the original functionality of a blank roll slate, which most users probably won't be looking to have once they've setup their rolls.
- Disable Save Rolls button if the Saved Rolls section is empty.

**Comment by JasonCostanza** [comment]
Definitely agree here. I see some iconography we can perhaps rely on and instead of having [Save], [Save Rolls] and [Load Rolls] we could leverage some of these buttons to reduce sidebar estate while still communicating their purpose. I wonder too if we should implement a settings menu to contain options such as:
- Automatically load locally stored rolls library when joining a session
- Automatically store saved rolls in local storage

For iconography, perhaps leverage these:
- `ts-icon-copy` || Save to local storage
- `ts-icon-paste` || Load from local storage
- `ts-icon-return` || Clear session storage
- `ts-icon-warning` or `ts-icon-link-broken` || Rolls that are saved but not stored in local storage

Any concern on overusing iconography so we save having to create new assets? I'd love to keep visual language consistent between symbiote and Talespire where possible especailly since we have such great icon assets available to us to use as symbiote makers

**Comment by PanoramicPanda** [comment]
The settings menu is a good call for auto-save and auto-load.

I love the idea of iconography use, however, text certainly makes things clearer about what the button is doing or the state of things. Which is important for the user to know at a glance. I think it's worth having a branch that is only trying out iconography buttons and see how it feels at least. I think a combination would work best, though that makes things technically larger 😂.

`ts-icon-chevron-double-up` is the icon used by TS for unsaved changes on the board.

I like the idea of using `ts-icon-link` and `ts-icon-link-broken` to indicate if a roll has been saved within session storage.

I also think we can get some good icons from https://game-icons.net/ we could include if one of TS's icons don't quite fit.

**Comment by PanoramicPanda** [comment]
Saving a Roll should auto-clear if it doesn't already - not something I paid attention to.

**Comment by JasonCostanza** [comment]
> Saving a Roll should auto-clear if it doesn't already - not something I paid attention to.

I have been on the fence about this over the past couple days because I see pros and cons to both. Clearing it makes sense, you make it, save it, and it clears for the next one. The other side of the coin is that I made it, save it before I forget, but immediately need that roll so I am ready to throw it. If we auto-clear, the user has to then find it in their list which may be easy, hopefully 😅 

Perhaps we add an option in the settings menu I mentioned so it's player's choice

**Comment by PanoramicPanda** [comment]
For save and load iconography, I think using these two (in reverse maybe since the dice space is above the buttons?) would be best - its the fairly universal save icon.

https://game-icons.net/1x1/delapouite/save.html
https://game-icons.net/1x1/delapouite/load.html
