### ISSUE TITLE
Iconography for Roll Buttons

### ISSUE THREAD

**Issue by PanoramicPanda** [JasonCostanza/Dice-Vault#31]
Wanted to track this in a single card.
Instead of having text for:

- Quick Roll/Roll
- Disadvantage
- Advantage
- Best of Three
- x2 Dice

What Iconography can we use instead?

Two routes:
- Sticking with ts-icons and what we can do with those.
- Making icons, preferably using game-icons.net for a similar look and feel.

Here are my proposals:
- Quick Roll/Roll: https://game-icons.net/1x1/delapouite/rolling-dice-cup.html
- Disadvantage:  `ts-icon-d20` with a `D` or a `-` super-imposed on it. Or a red-tinted `ts-icon-d20-grey` with the same.
- Advantage: Green tinted `ts-icon-d20-grey` with a `A` or a `+` on it.
- Best of Three: Green Tinted `ts-icon-d20-grey` with a `3` on it.
- x2 Dice: Either `ts-icon-d12` with a x2 super-imposed on it or https://game-icons.net/1x1/delapouite/rolling-dices.html (with x2 as well)

Doing this will allow for one row of uniform buttons for all of these on Saved Roll cards.

**Comment by JasonCostanza** [comment]
I didn't know about game-icons.net, that's cool!

I think I like the idea of "D" and "A" on top of the icon. I think + and - are too tied to mathematical addition and subtraction so people would wonder what's being added or subtracted or thinking "It's the results minus 1d20" which isn't true. The other option, we could have a button that is 3 states and it starts at normal, click 1 time goes to advantage, click twice goes to disadvantage, and 3rd time back to normal.

So there's two scenarios for critically hitting because some tables use 2x the result `((1d4)*2)=result` and some use double the number of damage dice `(1*2d4)=result` so it'll be important we handle both situations somehow. Or, we only handle 2x the result and if they need to roll double the quantity they just throw again and add that `a+b`. I could see this being in the options menu for "Critical Hit Rule: `Double Result` || `Double Dice Quantity`" I think I like the idea of using the dice cup. I'm worried we're overusing the `ts-icon-d20` already so we should try to visually distinguish if possible. Thoughts?

I think for Best of 3 we should consider labelling "Bo3" which hopefully won't take up too much space. A dice with a plain 3 on it to me means +3 (modifier) or 3x the dice `a+b+c`. In this case we're talking `a` OR `b` OR `c`.

Did I miss any ideas to respond to?

**Comment by PanoramicPanda** [comment]
The button at 3 states is still the original problem - having to click multiple times to roll at the different types. The barrier to rolling should be 1 click for all options.

I agree with D/A. And I agree `3` is a little too vague. I'll try `Bo3` when I go to implement this.

**Comment by JasonCostanza** [comment]
Yeah good point on the barrier, not much of a change in retrospect. Sounds
great to me!
