### ISSUE TITLE
Feature Request: Additional crit multiplication modifiers

### ISSUE THREAD

**Issue by Kara-Nash** [JasonCostanza/Dice-Vault#43]
**Describe the feature or improvement you would like**
Can I request more crit modifiers? Double is good, but 3x and 4x crit modifiers would make this more versatile at least for playing 3.5 DnD in Talespire.

x3 for axes, punching daggers, long spears, spears, handaxe, battleaxes, polearms, etc, 
x4 for light and heavy picks, scythes, hooked gnome hammers.
1.5x - just recalled metamagic feats. This would be very useful as well.

**Describe alternatives you've considered**
No alternatives available that don't suffer from bandwidth issues. DDice is too greedy for us to use as a group.

**Is your feature request related to a problem or frustration?**

**Additional context**

**Comment by Kara-Nash** [comment]
Yes, total sum of dice and modifier. 
I don't recall a scenario where the modifier would be applied afterwards.

**Comment by JasonCostanza** [comment]
Cool, makes sense. I have it prototyped up already and I'll release it with the next version which will be the roll groups. I need more time to work on that though, it's taking a bit longer than I had hoped because I'm not a great programmer :) but once that's done, your 3x and 4x will ship alongside and apply to all the groups

**Comment by JasonCostanza** [comment]
This will be released as a fast-follow to 2.0. I have the work completed just going through some testing and will release soon @Kara-Nash
